version: "3.8"
services:
  # Redis コンテナ
  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--bind", "0.0.0.0"]
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=jiro0102
    volumes:
      - redis-data:/data

volumes:
  redis-data: